### ISSUE TITLE
no matches for kind "Trigger" in version "triggers.tekton.dev/v1alpha1" with OCP 4.5.11

### ISSUE THREAD

**Issue by tux1980** [openshift/pipelines-tutorial#107]
Morning,

my second Issue I did recognize after creating the trigger-template and the trigger-binding (which have been successful). 
Always with trying apply the "trigger" yaml file I get the follow error message: 

"error: unable to recognize "03_trigger.yaml": no matches for kind "Trigger" in version "triggers.tekton.dev/v1alpha1""

YAML Content: 
 ---------------
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: vote-trigger
spec:
  serviceAccountName: pipeline
  bindings:
   - ref: vote-app
  template:
   name: vote-app
 ---------------

I did try out a couple of hints and clues in the GIT articles, without being successful yet. 

TA
Wolfgang

**Comment by fleason** [comment]
I am getting same error on IBM ROKS:
```
[@localhost dev]$ oc version
Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.5.15
Kubernetes Version: v1.18.3+2fbd7c7
[@localhost dev]$ tkn version
Client version: 0.11.0
Pipeline version: v0.17.3
Triggers version: v0.6.1
[@localhost dev]$ oc create -f pipelines-tutorial/03_triggers/03_trigger.yaml 
error: unable to recognize "pipelines-tutorial/03_triggers/03_trigger.yaml": no matches for kind "Trigger" in version "triggers.tekton.dev/v1alpha1"
```
I have opened a Case with IBM Support.  CS2042101

**Comment by fleason** [comment]
I received help from @chaseo on #armada-users. He provided the following patch:
`kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml`
This cleared the problem and the Trigger was created.
