### ISSUE TITLE
json: unknown field "volumeClaimTemplate"

### ISSUE THREAD

**Issue by fleason** [openshift/pipelines-tutorial#108]
Following the demo on IBM Cloud ROKS. Not sure where to go. Are there logs that could provide more detail?

>[f*****@localhost ~]$ tkn pipeline start build-and-deploy \
>     -w name=shared-workspace,volumeClaimTemplateFile=https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/01_pipeline/03_persistent_volume_claim.yaml \
>     -p deployment-name=vote-api \
>     -p git-url=http://github.com/openshift-pipelines/vote-api.git \
>     -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api \
> 
>Error: admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "volumeClaimTemplate"`

OpenShift version 4.4.20

tkn version
Client version: 0.11.0
Pipeline version: v0.11.3
Triggers version: v0.4.0

oc version
Client Version: 4.5.0-202005291417-9933eb9
Server Version: 4.4.20
Kubernetes Version: v1.17.1+6af3663

**Comment by fleason** [comment]
I changed the oc client version. Same problem.
```
[f****@localhost ~]$ oc version
Client Version: 4.4.0-202005290638-1960dd7
Server Version: 4.4.20
Kubernetes Version: v1.17.1+6af3663
```

**Comment by ppitonak** [comment]
Hi, `volumeClaimTemplate` is a feature introduced in Pipelines 1.1 (Tekton 0.14.3). Since you have older version of Pipelines, follow the instruction on this branch https://github.com/openshift/pipelines-tutorial/tree/release-tech-preview-1

**Comment by fleason** [comment]
> Hi, `volumeClaimTemplate` is a feature introduced in Pipelines 1.1 (Tekton 0.14.3). Since you have older version of Pipelines, follow the instruction on this branch https://github.com/openshift/pipelines-tutorial/tree/release-tech-preview-1

Issue resolved. Thanks.

**Comment by fleason** [comment]
@ppitonak advice resolved problem.
