### ISSUE TITLE
no matches for kind "Task" in version "tekton.dev/v1alpha1"

### ISSUE THREAD

**Issue by jralmaraz** [openshift/pipelines-tutorial#11]
Hi,

I am not able to complete the tutorial with an error related with the task deployment. I am not sure yet what dependency I'm missing, so thought of raising an issue for it:

joalmaraz$ oc create -f https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml
error: unable to recognize "https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml": no matches for kind "Task" in version "tekton.dev/v1alpha1"

Or locally referenced:

pipelines-tutorial joalmaraz$ oc create -f openshift-client-task.yaml
error: unable to recognize "openshift-client-task.yaml": no matches for kind "Task" in version "tekton.dev/v1alpha1"

joalmaraz$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://****:6443
kubernetes v1.14.0+42b6806

Version | State | Started | Completed
4.2.0-0.okd-2019-06-16-213454 | Completed | Jun 17, 10:11 am | Jun 17, 10:31 am

Operator is installed:

![image](https://user-images.githubusercontent.com/13877691/61191198-b6be6580-a6ea-11e9-979e-43166563b3e4.png)

Thanks.

Jose

**Comment by jralmaraz** [comment]
Redone install steps and it's now working.

![image](https://user-images.githubusercontent.com/13877691/61430920-fdbc8d00-a96e-11e9-9b94-9cd16dcb0269.png)

**Comment by danielhelfand** [comment]
@jralmaraz For clarification, you had to reinstall OpenShift Pipelines to resolve the issue? I also faced this issue. 

Do you remember how you installed OpenShift Pipelines originally? Did it work at any point with your original install? 

This came up for me after installing OpenShift Pipelines and running this tutorial successfully. Of note, there were others working on my OpenShift cluster also doing work with OpenShift Pipelines, so I'm not sure if there was something done that I was not aware of.

**Comment by Mrchenli** [comment]
for me , login with kubeadmin solve this problem

**Comment by bostrt** [comment]
Saw the same issue. Resolution was to uninstall and delete the OpenShift Piplines Operator. Create the `openshift-pipelines` namespace manually and reinstall Pipelines Operator. Seems fine now.

**Comment by sp1d3rino** [comment]
In my case I needed to change the apiVersion from v1beta1 to v1alpha1
