### ISSUE TITLE
Trigger Pipeline fails

### ISSUE THREAD

**Issue by nsevalia** [openshift/pipelines-tutorial#113]
Trying this tutorial on Openshift 4.4 environment. In the Trigger pipeline section, when tried to run this command it throws error

_tkn pipeline start build-and-deploy -w name=shared-workspace, volumeClaimTemplateFile=https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/01_pipeline/03_persistent_volume_claim.yaml -p deployment-name=vote-api -p git-url=http://github.com/openshift-pipelines/vote-api.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api_

_Error: admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "volumeClaimTemplate"_

Am I missing something here?
_(Webhook content comes below this section in the tutorial)_

**Comment by fleason** [comment]
See https://github.com/openshift/pipelines-tutorial/issues/108. You have to use a different branch of the tutorial.
