### ISSUE TITLE
Unable to create trigger 

### ISSUE THREAD

**Issue by jeffwarnica** [openshift/pipelines-tutorial#133]
[jwarnica@jwarnica crc-linux-1.22.0-amd64]$ oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/03_triggers/03_trigger.yaml
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/03_triggers/03_trigger.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "ref"

OpenShift Version: 4.6.15
redhat-openshift-pipelines-operator.v1.2.3

**Comment by san-biqmind** [comment]
Please use the branch **release-tech-preview-2** branch on OpenShift 4.6.x. The same has been referenced in the Red Hat documentation https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html-single/pipelines/index#installing-pipelines

I had the same issue using the **master** branch.

santhoshi@Azure:~$ oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/release-tech-preview-2/03_triggers/02_template.yaml
triggertemplate.triggers.tekton.dev/vote-app created
santhoshi@Azure:~$ oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/release-tech-preview-2/03_triggers/01_binding.yaml
triggerbinding.triggers.tekton.dev/vote-app created
santhoshi@Azure:~$ oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/release-tech-preview-2/03_triggers/03_event_listener.yaml
eventlistener.triggers.tekton.dev/vote-app created
santhoshi@Azure:~$ oc expose svc el-vote-app
route.route.openshift.io/el-vote-app exposed

Tested on ARO (Azure Red Hat OpenShift): 4.6.17
redhat-openshift-pipelines-opertor.v1.2.3
