### ISSUE TITLE
README suggests try.openshift.com, but users cannot install operators

### ISSUE THREAD

**Issue by ktdreyer** [openshift/pipelines-tutorial#152]
When I go to try.openshift.com, my user account is named DevSandbox. This user does not appear to have permissions to install operators, so I cannot proceed with the pipelines tutorial in this environment.

Is there another way to get administrator access to the try.openshift.com environments, or some other clues we could give users in the README?

**Comment by nikhil-thomas** [comment]
hi, at present OpenShift Pipelines Operator is not supported on try.openshift.com. Let me try to help you with the 2nd question.

> or some other clues we could give users in the README?

@siamaksade @vdemeester 

@ktdreyer feel free to reach us on `tektoncd-pipeline-dev`channel on coreos slack. 🧑‍💻

**Comment by ktdreyer** [comment]
Thanks. 

Should we remove all `try.openshift.com` references in this tutorial, then?

What would you recommend instead?

**Comment by vdemeester** [comment]
Note that it doesn't work with the "Developer sandbox" (first box) but it should work with the other options (Managed Services and Self-Managed). We may want to add in the README that it doesn't run on "Developer sandbox" (yet).
