### ISSUE TITLE
trigger failed to trig the pipeline with "x509: certificate signed by unknown authority "

### ISSUE THREAD

**Issue by sunnyguohua** [openshift/pipelines-tutorial#164]
OCP 4.10.26
pipeline operator 1.8

The web hook from github has been delievered with 202:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/6479673/194703259-db315cb2-1250-4548-8da4-0635f15f1e6a.png">

but no pipelinerun been kickoff.
And, I found following message from event listener:

`{"level":"error","ts":"2022-10-08T09:53:48.696Z","logger":"eventlistener","caller":"sink/sink.go:381","msg":"Post \"https://tekton-triggers-core-interceptors.openshift-pipelines.svc:8443/github\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"tekton-triggers-core-interceptors.openshift-pipelines.svc\")","commit":"d460f02","eventlistener":"vote-app","namespace":"pipelines-tutorial","/triggers-eventid":"93a37799-8166-4828-8494-f6833d40b102","eventlistenerUID":"809a90ad-0439-490a-97cc-7fa4592a56a9","/triggers-eventid":"93a37799-8166-4828-8494-f6833d40b102","/trigger":"vote-trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:381\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:196"}`

**Comment by YevheniiPokhvalii** [comment]
I had a similar problem. You need to restart Tekton interceptor pod. It refused to update a certificate in my case.
