### ISSUE TITLE
getting an error: the API version in the data (tekton.dev/v1beta1) does not match the expected API version (tekton.dev/v1)

### ISSUE THREAD

**Issue by barrybrianbarrios** [openshift/pipelines-tutorial#166]
tkn pipeline start build-and-deploy -w name=shared-workspace,volumeClaimTemplateFile=03_persistent_volume_claim.yaml -p deployment-name=pipelines-vote-api -p git-url=https://github.com/openshift/pipelines-vote-api.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-api --use-param-defaults
Error: the API version in the data (tekton.dev/v1beta1) does not match the expected API version (tekton.dev/v1)

**Comment by gforster** [comment]
Had the same issue. Just needed to update `tkn`, the tekton cli package.

**Comment by alfred4ibm** [comment]
same here update from tkn 0.21 to 0.31 solve my issue (macOS) : https://github.com/tektoncd/cli/releases

**Comment by rbaumgar** [comment]
see https://github.com/openshift/pipelines-tutorial/pull/168

**Comment by piyush-garg** [comment]
We can help on this if you can provide some details with respect to tkn version, pipeline version etc.

This should not happen if you upgrade to latest version of tkn. Ideally this is happening if you are using old tkn with new pipeline version

**Comment by rbaumgar** [comment]
In the meantime, tekton objects are version v1 and are no longer v1beta. So an update would be useful.
