### ISSUE TITLE
Pipeline tutorial fails on 'crc-macos-1.0.0-beta.5'

### ISSUE THREAD

**Issue by brujoand** [openshift/pipelines-tutorial#22]
When following this tutorial with the crc-macos-1.0.0-beta.5 local install of openshift, I end up with this: https://gist.github.com/brujoand/72a564d1cd7d89586a7df181753457f4 which is the output log with the mvn download lines grepped out. 

I can't really tell what the problem is. But this looks problematic:
> [build : image-digest-exporter-generate-j8j8x] 2019/09/30 12:19:12 ImageResource petclinic-image doesn't have an index.json file: stat /builder/home/image-outputs/image/index.json: no such file or directory

Also this one at the end:
> [deploy : oc] Error: unknown command "$(inputs.params.ARGS)" for "oc"

Any pointers on how to debug this?

**Comment by danielhelfand** [comment]
@brujoand What version of Tekton pipelines do you have installed? You can tell by the operator that was installed.

**Comment by brujoand** [comment]
@danielhelfand it's the openshift-pipelines-operator.v0.5.2 

Edit: oh wow that's quite old.

**Comment by piyush-garg** [comment]
@brujoand You need to make one change in openshift-client task

 - Change `$(inputs.params.ARGS)` to `${inputs.params.ARGS}`

Please let us know if you face any other issue.

**Comment by brujoand** [comment]
Thanks @piyush-garg that solved my issue :)
