### ISSUE TITLE
 MAVEN_CLEAR_REPO=${inputs.params.MAVEN_CLEAR_REPO}: bad substitution

### ISSUE THREAD

**Issue by danieloh30** [openshift/pipelines-tutorial#29]
I'm trying to retest this tutorial to make sure if this is still working on OCP 4.1 since I'm done all the steps successfully a few weeks ago. The PipelineRun is failed as below:

➜  spring-petclinic git:(master) tkn pipeline logs -f                               
? Select pipeline : petclinic-deploy-pipeline
? Select pipelinerun : petclinic-deploy-pipeline-run-xlmw9 started 4 seconds ago
[build : create-dir-image-g87x8] {"level":"warn","ts":1571376051.427172,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
[build : create-dir-image-g87x8] {"level":"info","ts":1571376051.4284658,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/output/image\"; output "}

[build : git-source-petclinic-git-svt2v] {"level":"warn","ts":1571376051.6579278,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
[build : git-source-petclinic-git-svt2v] {"level":"info","ts":1571376054.3768287,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/spring-projects/spring-petclinic @ master in path /workspace/source"}

[build : gen-env-file] /bin/sh: MAVEN_CLEAR_REPO=${inputs.params.MAVEN_CLEAR_REPO}: bad substitution

Sometimes I have different errors:
[jboss@workspacem6t97jyjwma48bkf payment-service]$ tkn pipeline logs -f
? Select pipeline : petclinic-deploy-pipeline
? Select pipelinerun : petclinic-deploy-pipeline-run-72v9r started 17 seconds ago

[build : create-dir-image-sl8vk] {"level":"warn","ts":1571749550.4025996,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from koda
ta failed: open /var/run/ko/HEAD: no such file or directory"}
[build : create-dir-image-sl8vk] {"level":"info","ts":1571749550.403944,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c
mkdir -p /workspace/output/image\"; output "}

[build : git-source-petclinic-git-tcg4m] {"level":"warn","ts":1571749551.1254249,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID f
rom kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
[build : git-source-petclinic-git-tcg4m] {"level":"info","ts":1571749553.8468623,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://gi
thub.com/spring-projects/spring-petclinic @ master in path /workspace/source"}

[build : generate] Build failed
[build : generate] ERROR: An error occurred: stat ${inputs.params.PATH_CONTEXT}: no such file or directory

failed to get logs for task build : container step-generate has failed  : Error

**Comment by siamaksade** [comment]
Are you using OpenShift Pipelines 0.7?

**Comment by danieloh30** [comment]
I'm using Operator in OCP 4.1 but I installed it via oc apply --filename https://storage.googleapis.com/tekton-releases/latest/release.yaml. It looks at the latest one. As you said, I'll try to install an operator for testing this then will update you on the result.

**Comment by sthaha** [comment]
`${...}` is no more supported in `0.7` and above. Could you please provide link to the task definition that you are executing and the `tkn version` ?

**Comment by danieloh30** [comment]
Client version: v0.4.0

I have another error like:
Missing or invalid Task pipelines-demo/s2i-java-8: pods "petclinic-s2i-pipeline-run-7qfhc-build-s2i-4kc45-pod-49a76c" is forbidden: unable to validate against any security context constraint: [spec.containers[4].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[5].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[4].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[5].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
