### ISSUE TITLE
error copying layers and metadata

### ISSUE THREAD

**Issue by danieloh30** [openshift/pipelines-tutorial#33]
@siamaksade 
I'm testing this tutorial on ocp 4.2 using tkn cli v0.4.0 and I'm facing this error:

build-s2i : push] error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared,overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev,metacopy=on]image-registry.openshift-image-registry.svc:5000/pipelines-demo/spring-petclinic:latest" to "docker://image-registry.openshift-image-registry.svc:5000/pipelines-demo/spring-petclinic:latest": Error writing blob: Error initiating layer upload to /v2/pipelines-demo/spring-petclinic/blobs/uploads/ in image-registry.openshift-image-registry.svc:5000: unauthorized: authentication required

**Comment by siamaksade** [comment]
Looks like your service account does not have the correct credentials. Could you paste the PipelineRun YAML here?

**Comment by danieloh30** [comment]
`apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-s2i-pipeline-run-
  selfLink: >-
    /apis/tekton.dev/v1alpha1/namespaces/pipelines-demo/pipelineruns/petclinic-s2i-pipeline-run-xr4kt
  resourceVersion: '422427'
  name: petclinic-s2i-pipeline-run-xr4kt
  uid: f82a1370-f9e4-11e9-8827-1239f15c92b6
  creationTimestamp: '2019-10-29T00:42:22Z'
  generation: 1
  namespace: pipelines-demo
  labels:
    tekton.dev/pipeline: petclinic-s2i-pipeline
spec:
  pipelineRef:
    name: petclinic-s2i-pipeline
  podTemplate: {}
  resources:
    - name: app-git
      resourceRef:
        name: petclinic-git
    - name: app-image
      resourceRef:
        name: petclinic-image
  serviceAccount: ''
  timeout: 1h0m0s
status:
  completionTime: '2019-10-29T00:46:42Z'
  conditions:
    - lastTransitionTime: '2019-10-29T00:46:42Z'
      message: TaskRun petclinic-s2i-pipeline-run-xr4kt-build-s2i-2bfb6 has failed
      reason: Failed
      status: 'False'
      type: Succeeded
  startTime: '2019-10-29T00:42:22Z'
  taskRuns:
    petclinic-s2i-pipeline-run-xr4kt-build-s2i-2bfb6:
      pipelineTaskName: build-s2i
      status:
        completionTime: '2019-10-29T00:46:42Z'
        conditions:
          - lastTransitionTime: '2019-10-29T00:46:42Z'
            message: >-
              "step-push" exited with code 1 (image:
              "quay.io/buildah/stable@sha256:fd3a43c92168461c2076715352395a46236b1c21aa80bdd91c6e6fee7c4ecb4c");
              for logs run: kubectl -n pipelines-demo logs
              petclinic-s2i-pipeline-run-xr4kt-build-s2i-2bfb6-pod-260226 -c
              step-push
            reason: Failed
            status: 'False'
            type: Succeeded
        podName: petclinic-s2i-pipeline-run-xr4kt-build-s2i-2bfb6-pod-260226
        startTime: '2019-10-29T00:44:34Z'
        steps:
          - container: step-gen-env-file
            imageID: >-
              quay.io/openshift-pipeline/s2i@sha256:59172242f74d18af4cd325ca42b333f45456119c88ccc4b637d8a48ca2ecb1cc
            name: gen-env-file
            terminated:
              containerID: >-
                cri-o://26ae352e7b7cd45f28c7ba2d4bca13320ae391a6dc09ea2a7cf8621a9427bd96
              exitCode: 0
              finishedAt: '2019-10-29T00:45:01Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:57Z'
          - container: step-generate
            imageID: >-
              quay.io/openshift-pipeline/s2i@sha256:59172242f74d18af4cd325ca42b333f45456119c88ccc4b637d8a48ca2ecb1cc
            name: generate
            terminated:
              containerID: >-
                cri-o://86d7bdd80fd742c82380216d2878657e20aa47d48d967b900872e2c250935ae5
              exitCode: 0
              finishedAt: '2019-10-29T00:45:01Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:57Z'
          - container: step-build
            imageID: >-
              quay.io/buildah/stable@sha256:fd3a43c92168461c2076715352395a46236b1c21aa80bdd91c6e6fee7c4ecb4c
            name: build
            terminated:
              containerID: >-
                cri-o://a4e625de116f66840012c3811195c0644291fd562e60e464c978770d9e30b4c6
              exitCode: 0
              finishedAt: '2019-10-29T00:46:40Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:58Z'
          - container: step-push
            imageID: >-
              quay.io/buildah/stable@sha256:fd3a43c92168461c2076715352395a46236b1c21aa80bdd91c6e6fee7c4ecb4c
            name: push
            terminated:
              containerID: >-
                cri-o://8e39fb558abf2f6cdefdb418cdb74b8246e5bf05e0383e877ed01b1411423517
              exitCode: 1
              finishedAt: '2019-10-29T00:46:41Z'
              reason: Error
              startedAt: '2019-10-29T00:44:59Z'
          - container: step-git-source-petclinic-git-w22tb
            imageID: >-
              quay.io/openshift-pipeline/tektoncd-pipeline-git-init@sha256:b9beb1d9e41e08923f6683467dae01bb1657fdbae2e19f08c4c866f26eef3e0d
            name: git-source-petclinic-git-w22tb
            terminated:
              containerID: >-
                cri-o://ffbec064ed7763caa4d56906fe9b00803b3ade2b7650b1318366d20fb17a13ad
              exitCode: 0
              finishedAt: '2019-10-29T00:45:01Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:56Z'
          - container: step-image-digest-exporter-69m98
            imageID: >-
              quay.io/openshift-pipeline/tektoncd-pipeline-imagedigestexporter@sha256:6eae183d9667b292e271f5f8db0cd8ab78df45d4f9e6a4f7a7ab057e014fce54
            name: image-digest-exporter-69m98
            terminated:
              containerID: >-
                cri-o://295bc024c3e5cb4300e0b43a480dbeb40e44afa5e421e843245401a17fa5298a
              exitCode: 0
              finishedAt: '2019-10-29T00:46:41Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:59Z'
          - container: step-create-dir-image-rbddp
            imageID: >-
              quay.io/openshift-pipeline/tektoncd-pipeline-bash@sha256:d2bfc0aa8801a44458378c399e5c5dca40c26907694bccc9d0391686c9af7c85
            name: create-dir-image-rbddp
            terminated:
              containerID: >-
                cri-o://ea2aa150623abd673f0f8c39a35e217fc4e18af3e2738e7c1e42d31d4eaf9701
              exitCode: 0
              finishedAt: '2019-10-29T00:45:00Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:56Z'
    petclinic-s2i-pipeline-run-xr4kt-int-test-phttv:
      pipelineTaskName: int-test
      status:
        completionTime: '2019-10-29T00:46:33Z'
        conditions:
          - lastTransitionTime: '2019-10-29T00:46:33Z'
            message: All Steps have completed executing
            reason: Succeeded
            status: 'True'
            type: Succeeded
        podName: petclinic-s2i-pipeline-run-xr4kt-int-test-phttv-pod-5a69e4
        startTime: '2019-10-29T00:44:34Z'
        steps:
          - container: step-test
            imageID: >-
              docker.io/library/maven@sha256:2c042eafa0e628753ca76949e07b960d40a4dd970c295af70db51ec51ca1d4ef
            name: test
            terminated:
              containerID: >-
                cri-o://ae9607451021b57458331c8648a581273696759275062374771311cd8d3f191e
              exitCode: 0
              finishedAt: '2019-10-29T00:46:33Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:44Z'
          - container: step-git-source-petclinic-git-z5qws
            imageID: >-
              quay.io/openshift-pipeline/tektoncd-pipeline-git-init@sha256:b9beb1d9e41e08923f6683467dae01bb1657fdbae2e19f08c4c866f26eef3e0d
            name: git-source-petclinic-git-z5qws
            terminated:
              containerID: >-
                cri-o://2a62bddfe5a64cdcded7b7002cedcce6df515fc7f83d12ab14d458f977a3da78
              exitCode: 0
              finishedAt: '2019-10-29T00:44:46Z'
              reason: Completed
              startedAt: '2019-10-29T00:44:44Z'
    petclinic-s2i-pipeline-run-xr4kt-unit-test-rxlhb:
      pipelineTaskName: unit-test
      status:
        completionTime: '2019-10-29T00:44:34Z'
        conditions:
          - lastTransitionTime: '2019-10-29T00:44:34Z'
            message: All Steps have completed executing
            reason: Succeeded
            status: 'True'
            type: Succeeded
        podName: petclinic-s2i-pipeline-run-xr4kt-unit-test-rxlhb-pod-9766b7
        startTime: '2019-10-29T00:42:22Z'
        steps:
          - container: step-test
            imageID: >-
              docker.io/library/maven@sha256:2c042eafa0e628753ca76949e07b960d40a4dd970c295af70db51ec51ca1d4ef
            name: test
            terminated:
              containerID: >-
                cri-o://01e02fbe87e6bd49cccfc335437b4cad5b77709f66e108f74783c99f09ee365b
              exitCode: 0
              finishedAt: '2019-10-29T00:44:33Z'
              reason: Completed
              startedAt: '2019-10-29T00:42:32Z'
          - container: step-git-source-petclinic-git-ptd6w
            imageID: >-
              quay.io/openshift-pipeline/tektoncd-pipeline-git-init@sha256:b9beb1d9e41e08923f6683467dae01bb1657fdbae2e19f08c4c866f26eef3e0d
            name: git-source-petclinic-git-ptd6w
            terminated:
              containerID: >-
                cri-o://fc3fe9c0a02d7a4ab828adb6c4b22cd6e2109ee77dabf3962c0b3260e62db629
              exitCode: 0
              finishedAt: '2019-10-29T00:42:39Z'
              reason: Completed
              startedAt: '2019-10-29T00:42:32Z'
`

**Comment by siamaksade** [comment]
How did you start this pipeline? No service account is defined

**Comment by danieloh30** [comment]
$ oc create -f http://bit.ly/pipelines-demo

$ tkn pipeline start petclinic-s2i-pipeline -n pipelines-demo

$ tkn pipeline logs -f -n pipelines-demo

**Comment by siamaksade** [comment]
That is not about this tutorial then! Please move it to the right repo:
https://github.com/siamaksade/openshift-pipelines-examples
