### ISSUE TITLE
Pipeline run fails with PVC issue

### ISSUE THREAD

**Issue by wernertod** [openshift/pipelines-tutorial#42]
I set up the tutorial pipeline on OCP 4.2 using the provided instructions. Afterwards, the pipeline looks as expected, with all checks returning the expected results.
When I run the pipline though, the run fails, because a PVC cannot be bound to a PV:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: petclinic-deploy-pipeline-run-nl62q-pvc
  namespace: pipelines-tutorial
  selfLink: >-
    /api/v1/namespaces/pipelines-tutorial/persistentvolumeclaims/petclinic-deploy-pipeline-run-nl62q-pvc
  uid: 41bae36f-104a-11ea-8e86-00000a10063b
  resourceVersion: '5774327'
  creationTimestamp: '2019-11-26T12:42:50Z'
  ownerReferences:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      name: petclinic-deploy-pipeline-run-nl62q
      uid: 41b42f70-104a-11ea-b7cb-00000a10063a
      controller: true
      blockOwnerDeletion: true
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
status:
  phase: Pending

Error event:
PVCpetclinic-deploy-pipeline-run-nl62q-pvc
NamespaceNSpipelines-tutorial
Nov 26, 1:47 pm
Generated from persistentvolume-controller
19 times in the last 4 minutes
no persistent volumes available for this claim and no storage class is set

I created a PV beforehand to service the PVC bind (no storageClass, volume mode Filesystem), but it doesn't get used:

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pipeline-storage
  selfLink: /api/v1/persistentvolumes/pipeline-storage
  uid: 02156811-102a-11ea-b7cb-00000a10063a
  resourceVersion: '5772668'
  creationTimestamp: '2019-11-26T08:51:59Z'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 10.16.4.176
    path: /data
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Available

How can I get this resolved?

**Comment by raffamendes** [comment]
Hi, can you please change the ```spec``` of you PV to the following to see if it works?
Just make sure you change the path
```yaml
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/pv0002
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
```

**Comment by wernertod** [comment]
Interesting! With hostPath it worked:
[deploy : oc] deploymentconfig.apps.openshift.io/spring-petclinic rolled out

Now the big question is: why did the NFS exported storage on the inf node not work.
I copied the configuration from the registry-storage PV.
Is this maybe related to the accessModes?
My PV has ReadWriteMany and the PVC from the tutorial has ReadWriteOnce.

**Comment by wernertod** [comment]
Turns out it was the accessModes. Once I set all three in the PV (I'm guessing that the ReadWriteOnce was the crucial one), the PVC bind also worked for the nfs PV.
Thanks @raffamendes !

**Comment by raffamendes** [comment]
Happy to help!!, just to clarify, the ```accessModes``` works on 4.2 as labels to actually match the PVC as per the [docs](https://docs.openshift.com/container-platform/4.2/storage/persistent-storage/persistent-storage-nfs.html#persistent-storage-nfs-provisioning_persistent-storage-nfs)
I'll close this issue since the problem was solved.

/close

**Comment by raffamendes** [comment]
ops, for a moment I forgot this not the tekton github :sweat_smile:

**Comment by wernertod** [comment]
No problem, I close it. Thanks again! :-)
