### ISSUE TITLE
The server doesn't have a resource type "kind: PipelineResource, apiVersion: tekton.dev/v1alpha1".

### ISSUE THREAD

**Issue by josequaresma** [openshift/pipelines-tutorial#5]
While going through this tutorial today on OpenShift 4.1.3 and the OpenShift Pipelines Operator v0.4.0, I get the error `The server doesn't have a resource type "kind: PipelineResource, apiVersion: tekton.dev/v1alpha1".` when trying to create the PipelineResources. Maybe I am doing something wrong, but I cannot see what

![image](https://user-images.githubusercontent.com/3469702/60460531-4d4b4b00-9c44-11e9-9240-13227490cccb.png)

**Comment by siamaksade** [comment]
Do you get the same error when creating via CLI? Could it be that pipeline operator was not ready yet?

**Comment by jralmaraz** [comment]
I am facing a similar thing, but with the task deployment, but not sure what dependency is missing:

joalmaraz$ oc create -f https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml
error: unable to recognize "https://raw.githubusercontent.com/tektoncd/catalog/master/openshift-client/openshift-client-task.yaml": no matches for kind "Task" in version "tekton.dev/v1alpha1"

Or locally referenced:

pipelines-tutorial joalmaraz$ oc create -f openshift-client-task.yaml 
error: unable to recognize "openshift-client-task.yaml": no matches for kind "Task" in version "tekton.dev/v1alpha1"

joalmaraz$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://****:6443
kubernetes v1.14.0+42b6806

Version | State | Started | Completed
4.2.0-0.okd-2019-06-16-213454 | Completed | Jun 17, 10:11 am | Jun 17, 10:31 am

Operator is installed:

![image](https://user-images.githubusercontent.com/13877691/61110161-f3f7dd00-a4c9-11e9-9a06-a4702847b1b0.png)

**Comment by codingarchitect** [comment]
I ran into the same issue, My issue was I missed this step
```
kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole=cluster-admin \
--user=$(gcloud config get-value core/account)
````
In my case I was using docker desktop for windows, So i had to run 
```
kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole=cluster-admin \
--user=docker-desktop
````
The user is the one found in kubernetes config file ~/.kube/config

Thanks,

**Comment by allexistence** [comment]
might be a problem because tekton is yet to be installed on machine
