### ISSUE TITLE
Following the tutorial first run ends with: "invalid input params: param types don't match the user-specified type: [TLSVERIFY]"

### ISSUE THREAD

**Issue by karstengresch** [openshift/pipelines-tutorial#51]
After following the tutoriaI step-by-step, I get:

```
invalid input params: param types don't match the user-specified type: [TLSVERIFY]
```

OCP 4.2 on AWS. cluster-admin permissions.

**Comment by sspeiche** [comment]
Looks like the `ClusterTask` `buildah` is missing the type definition of string (if you look at `s2i-python` it is correct, ie has the explicit type setting.

**Comment by sthaha** [comment]
Thanks for the report. This is a known bug and has been [fixed](https://github.com/openshift/tektoncd-pipeline-operator/pull/143) . A workaround until the PR is accepted into the OLM is to reapply the clustertasks in https://github.com/openshift/tektoncd-pipeline-operator/tree/master/deploy/resources/v0.8.0/addons/clustertasks

**Comment by nikhil-thomas** [comment]
@karstengresch, @sspeiche is right.
Ideally this should not happen as the OpenShift Pipeline mutating webhook should add the missing values like this. However, it looks like the clustertask got created in a very short window in which the webhook was being registered. As @sthaha mentioned we have pushed a patch.
The above comment will help you as a quick fix.

As soon as the patch merges and it is published in operatorhub, you will get the patch if your operator subscription approval strategy is `automatic`.

I shall post an update on this thread when the update becomes available on operatorhub.

**Comment by nikhil-thomas** [comment]
@karstengresch @sspeiche @sthaha 
we have pushed a fix to operator-hub.(https://github.com/operator-framework/community-operators/pull/995)

The operator should update automatically.

**Comment by karstengresch** [comment]
Thanks @sspeiche, @sthaha and @nikhil-thomas - that was fast!
