### ISSUE TITLE
Build error in step update-ui-image

### ISSUE THREAD

**Issue by marcoantonioni** [openshift/pipelines-tutorial#57]
Hi all,
tested on Openshift CRC 4.2.13

getting this error

web console:

update-ui-image

step-patch
Error from server (NotFound): deployments.extensions "ui" not found

command line:
....
[build-ui : image-digest-exporter-grtqg] {"level":"warn","ts":1579104550.7637124,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[build-ui : image-digest-exporter-grtqg] {"level":"info","ts":1579104550.7639525,"logger":"fallback-logger","caller":"imagedigestexporter/main.go:58","msg":"ImageResource api-image doesn't have an index.json file: stat /builder/home/image-outputs/image/index.json: no such file or directory"}

[apply-ui-manifests : git-source-api-repo-bgr9t] {"level":"warn","ts":1579104566.547371,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[apply-ui-manifests : git-source-api-repo-bgr9t] {"level":"info","ts":1579104569.0245762,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned http://github.com/openshift-pipelines/vote-api.git @ master in path /workspace/source"}

[apply-ui-manifests : apply] Applying manifests in k8s directory
[apply-ui-manifests : apply] deployment.apps/api configured
[apply-ui-manifests : apply] service/api unchanged
[apply-ui-manifests : apply] -----------------------------------

[update-ui-image : patch] Error from server (NotFound): deployments.extensions "ui" not found

failed to get logs for task update-ui-image : container step-patch has failed

**Comment by jorgemoralespou** [comment]
I got the same error and I did apply the deployment manually before running the pipeline and it worked. I'm assuming that the parallelization is not working properly.

We can even see executions like this:
![image](https://user-images.githubusercontent.com/78350/75376957-33e0c880-58d1-11ea-81c1-07cb51242a0d.png)

Which should have never progressed.

**Comment by christianh814** [comment]
I ran into this same issue

**Comment by hupiper** [comment]
I ran into this too. This appears to be an issue with using a secret to access github.  see https://github.com/tektoncd/pipeline/issues/1375

**Comment by whls** [comment]
@hupiper  I have the same issue too. but it seems that all repositories are public, Do we also need created a secret for github? And how can I  created a secret for github?

**Comment by whls** [comment]
@marcoantonioni  Excuse me, have you finally found the problem?
