### ISSUE TITLE
quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1 is not exist

### ISSUE THREAD

**Issue by kevinyu98** [openshift/pipelines-tutorial#67]
During investing this issue [pr38](https://github.com/kubeflow/kfp-tekton/issues/38), we noticed that this image is not exist. Can you help check?

**Comment by ckadner** [comment]
@kevinyu98 please add some detail to this issue

**Comment by ckadner** [comment]
```
Normal    Pulling   10m (x7 over 21m)     kubelet, 10.221.112.173  Pulling image "quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1"
Normal    BackOff   5m34s (x68 over 21m)  kubelet, 10.221.112.173  Back-off pulling image "quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1"
Warning   Failed    36s (x90 over 21m)    kubelet, 10.221.112.173  Error: ImagePullBackOff
```

The image `quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1` does not exist:
https://quay.io/repository/openshift-pipeline/tektoncd-pipeline-gsutil?tab=tags

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/issues/38#issuecomment-601468600_

**Comment by ckadner** [comment]
@kevinyu98 -- did you use the **[openshift/tektoncd-pipeline-operator](https://github.com/openshift/tektoncd-pipeline-operator)**?

[deploy/resources/v0.10.1/pipelines/release.yaml#L816](
/blob/740a7b1027be618066111bd73f327a702da645a4/deploy/resources/v0.10.1/pipelines/release.yaml#L816) refers to `image: quay.io/openshift-pipeline/tektoncd-pipeline-controller:v0.10.1`:
```YAML
    spec:
      serviceAccountName: tekton-pipelines-controller
      containers:
      - name: tekton-pipelines-controller
        image: quay.io/openshift-pipeline/tektoncd-pipeline-controller:v0.10.1
        args: [
          "-kubeconfig-writer-image", "quay.io/openshift-pipeline/tektoncd-pipeline-kubeconfigwriter:v0.10.1",
          "-creds-image", "quay.io/openshift-pipeline/tektoncd-pipeline-creds-init:v0.10.1",
          "-git-image", "quay.io/openshift-pipeline/tektoncd-pipeline-git-init:v0.10.1",
          "-nop-image", "quay.io/openshift-pipeline/tektoncd-pipeline-nop:v0.10.1",
          "-shell-image", "registry.access.redhat.com/ubi8/ubi-minimal:latest",
          "-gsutil-image", "quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1",
          "-entrypoint-image", "quay.io/openshift-pipeline/tektoncd-pipeline-entrypoint:v0.10.1",
          "-imagedigest-exporter-image", "quay.io/openshift-pipeline/tektoncd-pipeline-imagedigestexporter:v0.10.1",
          "-pr-image", "quay.io/openshift-pipeline/tektoncd-pipeline-pullrequest-init:v0.10.1",
          "-build-gcs-fetcher-image", "quay.io/openshift-pipeline/tektoncd-pipeline-gcs-fetcher:v0.10.1",
        ]
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        env:
```

**Comment by ckadner** [comment]
See [tektoncd-pipeline-operator/issues/239](https://github.com/openshift/tektoncd-pipeline-operator/issues/239):

@chmouel removed the image in commit [`tektoncd/pipeline@f1692b9`](https://github.com/tektoncd/pipeline/commit/f1692b9aaa688bbe0b666b4414df88f47237f728)

> Since upstream (ie pipeline) is not generating a binary wrapper anymore but using the google/cloud-sdk image directly..
> 
> I think in the mean time until we get this fixed you can update your deployment referencing this image directly...
> 
> @nikhil-thomas I have created openshift/tektoncd-pipeline#328 which would be used for next release, we can backport this to the release.yaml if you think so ? or wait for next release?

**Comment by ckadner** [comment]
@chmouel @nikhil-thomas -- how should we proceed here. Update some docs, add workarounds, change the operator, ...?
