### ISSUE TITLE
Tutorial throws error

### ISSUE THREAD

**Issue by tsterk** [openshift/pipelines-tutorial#78]
When running the tutorial, I'm getting this error in v0.10.7:
`
tkn pr describe build-and-deploy-ex8xsq
Name:              build-and-deploy-ex8xsq
Namespace:         pipelines-tutorial
Pipeline Ref:      build-and-deploy
Service Account:   pipeline
Timeout:           1h0m0s
Labels:
 tekton.dev/pipeline=build-and-deploy

Status

STARTED         DURATION    STATUS
3 minutes ago   0 seconds   Failed(PipelineValidationFailed)

Message

invalid input resources: TaskRun's declared resources didn't match usage in Task: [source]
`

**Comment by piyush-garg** [comment]
If you want to use the operator v0.10.7 then please use release-0.9 branch of the tutorial or if you want to use current master or release-tech-preview-1 of tutorial then please use operator 0.11.x
