### ISSUE TITLE
Error creating resources and running demo

### ISSUE THREAD

**Issue by Keyvan-rh** [openshift/pipelines-tutorial#82]
Using OCP 4.4.3 When running the tutorial, I'm getting this error in v0.10.7:
oc create -f 04_pipeline.yaml

error: unable to recognize "04_pipeline.yaml": no matches for kind "Pipeline" in version "tekton.dev/v1beta1"

the reason is the version of the API is v1beta1 but the operator is using/expecting v1alpha1
in the other hand if i do the same for the apply-mainfests it would error :

Error from server (BadRequest): error when creating "01_apply_manifest_task.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"

this time is because the schema has changed between alpha and beta. please make sure all yamls are using the same version and running with latest Pipline operator  (at the moment is v0.10.7)

**Comment by josequaresma** [comment]
I get similar error on OCP 4.3.0 and pipelines 0.10.7:
`error: unable to recognize "01_pipeline/01_apply_manifest_task.yaml": no matches for kind "Task" in version "tekton.dev/v1beta1"`

**Comment by DonSchenck** [comment]
I'm getting this as well.

**Comment by piyush-garg** [comment]
If you want to use the operator v0.10.7 then please use `release-0.9` branch of the tutorial or if you want to use current master or `release-tech-preview-1` of tutorial then please use operator 0.11.x

**Comment by Keyvan-rh** [comment]
Is it possible to use the 1.0.1 which is RedHat GAed and not the community one?

**Comment by piyush-garg** [comment]
@Keyvan-rh Yaa you can use that one also, it has v1beta1 resources.

**Comment by tux1980** [comment]
Hi, I'm getting this either:
error: unable to recognize "03_trigger.yaml": no matches for kind "Trigger" in version "triggers.tekton.dev/v1alpha1"
