### ISSUE TITLE
Build# and dynamic PipelineResource creation to be used as input to the next Task.

### ISSUE THREAD

**Issue by khteh** [openshift/pipelines-tutorial#90]
Is there a concept of build#? I would like to append that number as the last digit of version number (`1.0.0.Build#`). This version number string is then used to dynamically build a `PipelineResource` which is used as input in the next `Task`, to build and push the container image, for instance. How is this achieved? Thanks.

**Comment by ppitonak** [comment]
Hi, no there is no traditional concept of a build ID (as a sequence of natural numbers) but you could achive something similar with uid variable, see https://github.com/tektoncd/pipeline/blob/master/docs/variables.md

See also https://github.com/tektoncd/pipeline/issues/2957

**Comment by khteh** [comment]
Ok. I could probably use part of the `uid` variable value for image tagging. How do I define that tag dynamically in `PipelineResource` which is used by the `Task` which builds the container image based on information provided in `PipelineResource`? The reference code is hard-coding `:latest` in the image url.
