### ISSUE TITLE
Error in PipelineRun

### ISSUE THREAD

**Issue by khilmanoj** [openshift/pipelines-tutorial#91]
tkn pipeline start build-and-deploy \
    -w name=shared-workspace,claimName=source-pvc \
    -p deployment-name=vote-api \
    -p git-url=http://github.com/openshift-pipelines/vote-api.git \
    -p IMAGE=image-registry.openshift-image-registry.svc:5000/myproject/vote-api

TypeError
Description:

n is undefined
Component Trace:

in Unknown
    in div
    in div
    in div

6431/t.a@https://console-openshift-console.apps-crc.testing/static/pipelinerun-details-chunk-ee0c16b8da458300f498.min.js:1:175890
Fo@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:55337
Ks@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:98261
Bs@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:84008
Ns@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:81035
Ds@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:79608
di/<@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:41759
t.unstable_runWithPriority@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:144:3878
li@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:41488
di@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:41705
pi@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:41640
Is@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:136:79935
notify@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:23:75933
a</t.notifyNestedSubs@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:23:75503
f</n.notifySubscribers@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:65:2428
a</t.handleChangeWrapper@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:23:75571
v@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:17:122529
b/</</<@https://console-openshift-console.apps-crc.testing/static/main-chunk-dbccb664872199d7c81d.min.js:1:89823
dispatch@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:17:126016
l/<@https://console-openshift-console.apps-crc.testing/static/main-chunk-dbccb664872199d7c81d.min.js:1:84211
a@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:120:167477
k/<@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:120:167599
l@https://console-openshift-console.apps-crc.testing/static/vendors~main-chunk-5d16dae3ac38abab85aa.min.js:120:170236

**Comment by khilmanoj** [comment]
I changed the project to pipelines-tutorial and now the run fails with the following error:

invalid input params: didn't need these params but they were provided anyway: [IMAGE]

**Comment by khilmanoj** [comment]
Follow the latest doc --> https://docs.openshift.com/container-platform/4.4/pipelines/creating-applications-with-cicd-pipelines.html

**Comment by khilmanoj** [comment]
Follow the latest doc --> https://docs.openshift.com/container-platform/4.4/pipelines/creating-applications-with-cicd-pipelines.html

**Comment by ppitonak** [comment]
What version of OpenShift and Pipelines are you using?
